// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/tools/frames-volume-calc": {
    params: {};
  };
  "/tools/grade-differential": {
    params: {};
  };
  "/tools/building-envelope": {
    params: {};
  };
  "/grandpas-cabin-recipe": {
    params: {};
  };
  "/tools/erv-calculator": {
    params: {};
  };
  "/good/architecture": {
    params: {};
  };
  "/tools/do-not-use": {
    params: {};
  };
  "/good/consulting": {
    params: {};
  };
  "/assemblies/:id": {
    params: {
      "id": string;
    };
  };
  "/good/sunny-no1": {
    params: {};
  };
  "/sunny-home-no1": {
    params: {};
  };
  "/good/building": {
    params: {};
  };
  "/materials/:id": {
    params: {
      "id": string;
    };
  };
  "/roots": {
    params: {};
  };
  "/tools": {
    params: {};
  };
  "/good/guides": {
    params: {};
  };
  "/science/:id": {
    params: {
      "id": string;
    };
  };
  "/stories/:id": {
    params: {
      "id": string;
    };
  };
  "/tools/loads": {
    params: {};
  };
  "/scc-demo": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/explore": {
    params: {};
  };
  "/good/s": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/health/:key?": {
    params: {
      "key"?: string;
    };
  };
  "/about": {
    params: {};
  };
  "/mrgnt": {
    params: {};
  };
  "/mrgnt/magic-link": {
    params: {};
  };
  "/mrgnt/discord": {
    params: {};
  };
  "/mrgnt/logout": {
    params: {};
  };
  "/mrgnt/verify": {
    params: {};
  };
  "/mrgnt/login": {
    params: {};
  };
  "/mrgnt/gbs": {
    params: {};
  };
  "/path": {
    params: {};
  };
  "/path/faq-1": {
    params: {};
  };
  "/path/faq-2": {
    params: {};
  };
  "/path/faq-3": {
    params: {};
  };
  "/path/faq-4": {
    params: {};
  };
  "/path/faq-5": {
    params: {};
  };
  "/path/faq-6": {
    params: {};
  };
  "/path/faq-7": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/tools/frames-volume-calc" | "/tools/grade-differential" | "/tools/building-envelope" | "/grandpas-cabin-recipe" | "/tools/erv-calculator" | "/good/architecture" | "/tools/do-not-use" | "/good/consulting" | "/assemblies/:id" | "/good/sunny-no1" | "/sunny-home-no1" | "/good/building" | "/materials/:id" | "/roots" | "/tools" | "/good/guides" | "/science/:id" | "/stories/:id" | "/tools/loads" | "/scc-demo" | "/contact" | "/explore" | "/good/s" | "/health" | "/health/:key?" | "/about" | "/mrgnt" | "/mrgnt/magic-link" | "/mrgnt/discord" | "/mrgnt/logout" | "/mrgnt/verify" | "/mrgnt/login" | "/mrgnt/gbs" | "/path" | "/path/faq-1" | "/path/faq-2" | "/path/faq-3" | "/path/faq-4" | "/path/faq-5" | "/path/faq-6" | "/path/faq-7";
  };
  "routes/tools.frames-volume-calc.tsx": {
    id: "routes/tools.frames-volume-calc";
    page: "/tools/frames-volume-calc";
  };
  "routes/tools.grade-differential.tsx": {
    id: "routes/tools.grade-differential";
    page: "/tools/grade-differential";
  };
  "routes/tools.building-envelope.tsx": {
    id: "routes/tools.building-envelope";
    page: "/tools/building-envelope";
  };
  "routes/grandpas-cabin-recipe.tsx": {
    id: "routes/grandpas-cabin-recipe";
    page: "/grandpas-cabin-recipe";
  };
  "routes/tools.erv-calculator.tsx": {
    id: "routes/tools.erv-calculator";
    page: "/tools/erv-calculator";
  };
  "routes/good.architecture.tsx": {
    id: "routes/good.architecture";
    page: "/good/architecture";
  };
  "routes/tools.do-not-use.tsx": {
    id: "routes/tools.do-not-use";
    page: "/tools/do-not-use";
  };
  "routes/good.consulting.tsx": {
    id: "routes/good.consulting";
    page: "/good/consulting";
  };
  "routes/assemblies.$id.tsx": {
    id: "routes/assemblies.$id";
    page: "/assemblies/:id";
  };
  "routes/good.sunny-no1.tsx": {
    id: "routes/good.sunny-no1";
    page: "/good/sunny-no1";
  };
  "routes/sunny-home-no1.tsx": {
    id: "routes/sunny-home-no1";
    page: "/sunny-home-no1";
  };
  "routes/good.building.tsx": {
    id: "routes/good.building";
    page: "/good/building";
  };
  "routes/materials.$id.tsx": {
    id: "routes/materials.$id";
    page: "/materials/:id";
  };
  "routes/roots._index.tsx": {
    id: "routes/roots._index";
    page: "/roots";
  };
  "routes/tools._index.tsx": {
    id: "routes/tools._index";
    page: "/tools";
  };
  "routes/good.guides.tsx": {
    id: "routes/good.guides";
    page: "/good/guides";
  };
  "routes/science.$id.tsx": {
    id: "routes/science.$id";
    page: "/science/:id";
  };
  "routes/stories.$id.tsx": {
    id: "routes/stories.$id";
    page: "/stories/:id";
  };
  "routes/tools.loads.tsx": {
    id: "routes/tools.loads";
    page: "/tools/loads";
  };
  "routes/scc-demo.tsx": {
    id: "routes/scc-demo";
    page: "/scc-demo";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/explore.tsx": {
    id: "routes/explore";
    page: "/explore";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/good.s.tsx": {
    id: "routes/good.s";
    page: "/good/s";
  };
  "routes/health.tsx": {
    id: "routes/health";
    page: "/health" | "/health/:key?";
  };
  "routes/health.($key).tsx": {
    id: "routes/health.($key)";
    page: "/health/:key?";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/mrgnt.tsx": {
    id: "routes/mrgnt";
    page: "/mrgnt" | "/mrgnt/magic-link" | "/mrgnt/discord" | "/mrgnt/logout" | "/mrgnt/verify" | "/mrgnt/login" | "/mrgnt/gbs";
  };
  "routes/mrgnt.magic-link.tsx": {
    id: "routes/mrgnt.magic-link";
    page: "/mrgnt/magic-link";
  };
  "routes/mrgnt.discord.tsx": {
    id: "routes/mrgnt.discord";
    page: "/mrgnt/discord";
  };
  "routes/mrgnt._index.tsx": {
    id: "routes/mrgnt._index";
    page: "/mrgnt";
  };
  "routes/mrgnt.logout.tsx": {
    id: "routes/mrgnt.logout";
    page: "/mrgnt/logout";
  };
  "routes/mrgnt.verify.tsx": {
    id: "routes/mrgnt.verify";
    page: "/mrgnt/verify";
  };
  "routes/mrgnt.login.tsx": {
    id: "routes/mrgnt.login";
    page: "/mrgnt/login";
  };
  "routes/mrgnt.gbs.tsx": {
    id: "routes/mrgnt.gbs";
    page: "/mrgnt/gbs";
  };
  "routes/path.tsx": {
    id: "routes/path";
    page: "/path" | "/path/faq-1" | "/path/faq-2" | "/path/faq-3" | "/path/faq-4" | "/path/faq-5" | "/path/faq-6" | "/path/faq-7";
  };
  "routes/path._index.tsx": {
    id: "routes/path._index";
    page: "/path";
  };
  "routes/path.faq-1.tsx": {
    id: "routes/path.faq-1";
    page: "/path/faq-1";
  };
  "routes/path.faq-2.tsx": {
    id: "routes/path.faq-2";
    page: "/path/faq-2";
  };
  "routes/path.faq-3.tsx": {
    id: "routes/path.faq-3";
    page: "/path/faq-3";
  };
  "routes/path.faq-4.tsx": {
    id: "routes/path.faq-4";
    page: "/path/faq-4";
  };
  "routes/path.faq-5.tsx": {
    id: "routes/path.faq-5";
    page: "/path/faq-5";
  };
  "routes/path.faq-6.tsx": {
    id: "routes/path.faq-6";
    page: "/path/faq-6";
  };
  "routes/path.faq-7.tsx": {
    id: "routes/path.faq-7";
    page: "/path/faq-7";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/tools.frames-volume-calc": typeof import("./app/routes/tools.frames-volume-calc.tsx");
  "routes/tools.grade-differential": typeof import("./app/routes/tools.grade-differential.tsx");
  "routes/tools.building-envelope": typeof import("./app/routes/tools.building-envelope.tsx");
  "routes/grandpas-cabin-recipe": typeof import("./app/routes/grandpas-cabin-recipe.tsx");
  "routes/tools.erv-calculator": typeof import("./app/routes/tools.erv-calculator.tsx");
  "routes/good.architecture": typeof import("./app/routes/good.architecture.tsx");
  "routes/tools.do-not-use": typeof import("./app/routes/tools.do-not-use.tsx");
  "routes/good.consulting": typeof import("./app/routes/good.consulting.tsx");
  "routes/assemblies.$id": typeof import("./app/routes/assemblies.$id.tsx");
  "routes/good.sunny-no1": typeof import("./app/routes/good.sunny-no1.tsx");
  "routes/sunny-home-no1": typeof import("./app/routes/sunny-home-no1.tsx");
  "routes/good.building": typeof import("./app/routes/good.building.tsx");
  "routes/materials.$id": typeof import("./app/routes/materials.$id.tsx");
  "routes/roots._index": typeof import("./app/routes/roots._index.tsx");
  "routes/tools._index": typeof import("./app/routes/tools._index.tsx");
  "routes/good.guides": typeof import("./app/routes/good.guides.tsx");
  "routes/science.$id": typeof import("./app/routes/science.$id.tsx");
  "routes/stories.$id": typeof import("./app/routes/stories.$id.tsx");
  "routes/tools.loads": typeof import("./app/routes/tools.loads.tsx");
  "routes/scc-demo": typeof import("./app/routes/scc-demo.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/explore": typeof import("./app/routes/explore.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/good.s": typeof import("./app/routes/good.s.tsx");
  "routes/health": typeof import("./app/routes/health.tsx");
  "routes/health.($key)": typeof import("./app/routes/health.($key).tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/mrgnt": typeof import("./app/routes/mrgnt.tsx");
  "routes/mrgnt.magic-link": typeof import("./app/routes/mrgnt.magic-link.tsx");
  "routes/mrgnt.discord": typeof import("./app/routes/mrgnt.discord.tsx");
  "routes/mrgnt._index": typeof import("./app/routes/mrgnt._index.tsx");
  "routes/mrgnt.logout": typeof import("./app/routes/mrgnt.logout.tsx");
  "routes/mrgnt.verify": typeof import("./app/routes/mrgnt.verify.tsx");
  "routes/mrgnt.login": typeof import("./app/routes/mrgnt.login.tsx");
  "routes/mrgnt.gbs": typeof import("./app/routes/mrgnt.gbs.tsx");
  "routes/path": typeof import("./app/routes/path.tsx");
  "routes/path._index": typeof import("./app/routes/path._index.tsx");
  "routes/path.faq-1": typeof import("./app/routes/path.faq-1.tsx");
  "routes/path.faq-2": typeof import("./app/routes/path.faq-2.tsx");
  "routes/path.faq-3": typeof import("./app/routes/path.faq-3.tsx");
  "routes/path.faq-4": typeof import("./app/routes/path.faq-4.tsx");
  "routes/path.faq-5": typeof import("./app/routes/path.faq-5.tsx");
  "routes/path.faq-6": typeof import("./app/routes/path.faq-6.tsx");
  "routes/path.faq-7": typeof import("./app/routes/path.faq-7.tsx");
};